$(document).ready(function(){
    $("h3#one").click(function(q){
        q.preventDefault();
        $("#course1").toggle();
    });
});
$(document).ready(function(){
   $("h3#two").click(function(q){
       q.preventDefault();
       $("#course2").toggle();
   });
});
$(document).ready(function(){
   $("h3#three").click(function(q){
       q.preventDefault();
       $("#course3").toggle();
   });
});
$(document).ready(function(){
   $("h3#four").click(function(q){
       q.preventDefault();
       $("#course4").toggle();
   });
});
$(document).ready(function(){
   $("h3#five").click(function(q){
       q.preventDefault();
       $("#course5").toggle();
   });
});
$(document).ready(function(){
   $("h3#six").click(function(q){
       q.preventDefault();
       $("#course6").toggle();
   });
});



$(document).ready(function() {
    $("#a").click(function(q){
        q.preventDefault();
        $("#Swimming").toggle();
        $("#Diving").hide();
        $("#Soccer").hide();
        $("#Basketball").hide();
        $("#Cricket").hide();
        $("#Rugby").hide();
        $("#Hockey").hide();
        $("#Tennis").hide();
        $("#Volleyball").hide();
        $("#Boxing").hide();
        $("#MMA").hide();
        $("#Wrestling").hide();
        $("#Karate").hide();
        $("#Kickboxing").hide();
        $("#MusicTheory").hide();
        $("#Dance").hide();
        $("#SoundDesign").hide();
        $("#Painting").hide();
        $("#Sculpture").hide();
        $("#Photography").hide();
        $("#DigitalArt").hide();
        $("#DrawingDance").hide();
        $("#Illustration").hide();
        $("#Gymnastics").hide();
        $("#Fencing").hide();
        $("#SkiJumping").hide();
    })
 })

 $(document).ready(function() {
    $("#b").click(function(q){
        q.preventDefault();
        $("#Swimming").hide();
        $("#Diving").toggle();
        $("#Soccer").hide();
        $("#Basketball").hide();
        $("#Cricket").hide();
        $("#Rugby").hide();
        $("#Hockey").hide();
        $("#Tennis").hide();
        $("#Volleyball").hide();
        $("#Boxing").hide();
        $("#MMA").hide();
        $("#Wrestling").hide();
        $("#Karate").hide();
        $("#Kickboxing").hide();
        $("#MusicTheory").hide();
        $("#Dance").hide();
        $("#SoundDesign").hide();
        $("#Painting").hide();
        $("#Sculpture").hide();
        $("#Photography").hide();
        $("#DigitalArt").hide();
        $("#DrawingDance").hide();
        $("#Illustration").hide();
        $("#Gymnastics").hide();
        $("#Fencing").hide();
        $("#SkiJumping").hide();
    })
 })

 $(document).ready(function() {
    $("#c").click(function(q){
        q.preventDefault();
        $("#Swimming").hide();
        $("#Diving").hide();
        $("#Soccer").toggle();
        $("#Basketball").hide();
        $("#Cricket").hide();
        $("#Rugby").hide();
        $("#Hockey").hide();
        $("#Tennis").hide();
        $("#Volleyball").hide();
        $("#Boxing").hide();
        $("#MMA").hide();
        $("#Wrestling").hide();
        $("#Karate").hide();
        $("#Kickboxing").hide();
        $("#MusicTheory").hide();
        $("#Dance").hide();
        $("#SoundDesign").hide();
        $("#Painting").hide();
        $("#Sculpture").hide();
        $("#Photography").hide();
        $("#DigitalArt").hide();
        $("#DrawingDance").hide();
        $("#Illustration").hide();
        $("#Gymnastics").hide();
        $("#Fencing").hide();
        $("#SkiJumping").hide();
    })
 })

 $(document).ready(function() {
    $("#d").click(function(q){
        q.preventDefault();
        $("#Swimming").hide();
        $("#Diving").hide();
        $("#Soccer").hide();
        $("#Basketball").toggle();
        $("#Cricket").hide();
        $("#Rugby").hide();
        $("#Hockey").hide();
        $("#Tennis").hide();
        $("#Volleyball").hide();
        $("#Boxing").hide();
        $("#MMA").hide();
        $("#Wrestling").hide();
        $("#Karate").hide();
        $("#Kickboxing").hide();
        $("#MusicTheory").hide();
        $("#Dance").hide();
        $("#SoundDesign").hide();
        $("#Painting").hide();
        $("#Sculpture").hide();
        $("#Photography").hide();
        $("#DigitalArt").hide();
        $("#DrawingDance").hide();
        $("#Illustration").hide();
        $("#Gymnastics").hide();
        $("#Fencing").hide();
        $("#SkiJumping").hide();
    })
 })

 $(document).ready(function() {
    $("#e").click(function(q){
        q.preventDefault();
        $("#Swimming").hide();
        $("#Diving").hide();
        $("#Soccer").hide();
        $("#Basketball").hide();
        $("#Cricket").toggle();
        $("#Rugby").hide();
        $("#Hockey").hide();
        $("#Tennis").hide();
        $("#Volleyball").hide();
        $("#Boxing").hide();
        $("#MMA").hide();
        $("#Wrestling").hide();
        $("#Karate").hide();
        $("#Kickboxing").hide();
        $("#MusicTheory").hide();
        $("#Dance").hide();
        $("#SoundDesign").hide();
        $("#Painting").hide();
        $("#Sculpture").hide();
        $("#Photography").hide();
        $("#DigitalArt").hide();
        $("#DrawingDance").hide();
        $("#Illustration").hide();
        $("#Gymnastics").hide();
        $("#Fencing").hide();
        $("#SkiJumping").hide();
    })
 })

 $(document).ready(function() {
    $("#f").click(function(q){
        q.preventDefault();
        $("#Swimming").hide();
        $("#Diving").hide();
        $("#Soccer").hide();
        $("#Basketball").hide();
        $("#Cricket").hide();
        $("#Rugby").toggle();
        $("#Hockey").hide();
        $("#Tennis").hide();
        $("#Volleyball").hide();
        $("#Boxing").hide();
        $("#MMA").hide();
        $("#Wrestling").hide();
        $("#Karate").hide();
        $("#Kickboxing").hide();
        $("#MusicTheory").hide();
        $("#Dance").hide();
        $("#SoundDesign").hide();
        $("#Painting").hide();
        $("#Sculpture").hide();
        $("#Photography").hide();
        $("#DigitalArt").hide();
        $("#DrawingDance").hide();
        $("#Illustration").hide();
        $("#Gymnastics").hide();
        $("#Fencing").hide();
        $("#SkiJumping").hide();
    })
 })

 $(document).ready(function() {
    $("#g").click(function(q){
        q.preventDefault();
        $("#Swimming").hide();
        $("#Diving").hide();
        $("#Soccer").hide();
        $("#Basketball").hide();
        $("#Cricket").hide();
        $("#Rugby").hide();
        $("#Hockey").toggle();
        $("#Tennis").hide();
        $("#Volleyball").hide();
        $("#Boxing").hide();
        $("#MMA").hide();
        $("#Wrestling").hide();
        $("#Karate").hide();
        $("#Kickboxing").hide();
        $("#MusicTheory").hide();
        $("#Dance").hide();
        $("#SoundDesign").hide();
        $("#Painting").hide();
        $("#Sculpture").hide();
        $("#Photography").hide();
        $("#DigitalArt").hide();
        $("#DrawingDance").hide();
        $("#Illustration").hide();
        $("#Gymnastics").hide();
        $("#Fencing").hide();
        $("#SkiJumping").hide();
    })
 })

 $(document).ready(function() {
    $("#h").click(function(q){
        q.preventDefault();
        $("#Swimming").hide();
        $("#Diving").hide();
        $("#Soccer").hide();
        $("#Basketball").hide();
        $("#Cricket").hide();
        $("#Rugby").hide();
        $("#Hockey").hide();
        $("#Tennis").toggle();
        $("#Volleyball").hide();
        $("#Boxing").hide();
        $("#MMA").hide();
        $("#Wrestling").hide();
        $("#Karate").hide();
        $("#Kickboxing").hide();
        $("#MusicTheory").hide();
        $("#Dance").hide();
        $("#SoundDesign").hide();
        $("#Painting").hide();
        $("#Sculpture").hide();
        $("#Photography").hide();
        $("#DigitalArt").hide();
        $("#DrawingDance").hide();
        $("#Illustration").hide();
        $("#Gymnastics").hide();
        $("#Fencing").hide();
        $("#SkiJumping").hide();
    })
 })

 $(document).ready(function() {
    $("#i").click(function(q){
        q.preventDefault();
        $("#Swimming").hide();
        $("#Diving").hide();
        $("#Soccer").hide();
        $("#Basketball").hide();
        $("#Cricket").hide();
        $("#Rugby").hide();
        $("#Hockey").hide();
        $("#Tennis").hide();
        $("#Volleyball").toggle();
        $("#Boxing").hide();
        $("#MMA").hide();
        $("#Wrestling").hide();
        $("#Karate").hide();
        $("#Kickboxing").hide();
        $("#MusicTheory").hide();
        $("#Dance").hide();
        $("#SoundDesign").hide();
        $("#Painting").hide();
        $("#Sculpture").hide();
        $("#Photography").hide();
        $("#DigitalArt").hide();
        $("#DrawingDance").hide();
        $("#Illustration").hide();
        $("#Gymnastics").hide();
        $("#Fencing").hide();
        $("#SkiJumping").hide();
    })
 })

 $(document).ready(function() {
    $("#j").click(function(q){
        q.preventDefault();
        $("#Swimming").hide();
        $("#Diving").hide();
        $("#Soccer").hide();
        $("#Basketball").hide();
        $("#Cricket").hide();
        $("#Rugby").hide();
        $("#Hockey").hide();
        $("#Tennis").hide();
        $("#Volleyball").hide();
        $("#Boxing").toggle();
        $("#MMA").hide();
        $("#Wrestling").hide();
        $("#Karate").hide();
        $("#Kickboxing").hide();
        $("#MusicTheory").hide();
        $("#Dance").hide();
        $("#SoundDesign").hide();
        $("#Painting").hide();
        $("#Sculpture").hide();
        $("#Photography").hide();
        $("#DigitalArt").hide();
        $("#DrawingDance").hide();
        $("#Illustration").hide();
        $("#Gymnastics").hide();
        $("#Fencing").hide();
        $("#SkiJumping").hide();
    })
 })

 $(document).ready(function() {
    $("#k").click(function(q){
        q.preventDefault();
        $("#Swimming").toggle();
        $("#Diving").hide();
        $("#Soccer").hide();
        $("#Basketball").hide();
        $("#Cricket").hide();
        $("#Rugby").hide();
        $("#Hockey").hide();
        $("#Tennis").hide();
        $("#Volleyball").hide();
        $("#Boxing").hide();
        $("#MMA").toggle();
        $("#Wrestling").hide();
        $("#Karate").hide();
        $("#Kickboxing").hide();
        $("#MusicTheory").hide();
        $("#Dance").hide();
        $("#SoundDesign").hide();
        $("#Painting").hide();
        $("#Sculpture").hide();
        $("#Photography").hide();
        $("#DigitalArt").hide();
        $("#DrawingDance").hide();
        $("#Illustration").hide();
        $("#Gymnastics").hide();
        $("#Fencing").hide();
        $("#SkiJumping").hide();
    })
 })

 $(document).ready(function() {
    $("#l").click(function(q){
        q.preventDefault();
        $("#Swimming").hide();
        $("#Diving").hide();
        $("#Soccer").hide();
        $("#Basketball").hide();
        $("#Cricket").hide();
        $("#Rugby").hide();
        $("#Hockey").hide();
        $("#Tennis").hide();
        $("#Volleyball").hide();
        $("#Boxing").hide();
        $("#MMA").hide();
        $("#Wrestling").toggle();
        $("#Karate").hide();
        $("#Kickboxing").hide();
        $("#MusicTheory").hide();
        $("#Dance").hide();
        $("#SoundDesign").hide();
        $("#Painting").hide();
        $("#Sculpture").hide();
        $("#Photography").hide();
        $("#DigitalArt").hide();
        $("#DrawingDance").hide();
        $("#Illustration").hide();
        $("#Gymnastics").hide();
        $("#Fencing").hide();
        $("#SkiJumping").hide();
    })
 })

 $(document).ready(function() {
    $("#m").click(function(q){
        q.preventDefault();
        $("#Swimming").hide();
        $("#Diving").hide();
        $("#Soccer").hide();
        $("#Basketball").hide();
        $("#Cricket").hide();
        $("#Rugby").hide();
        $("#Hockey").hide();
        $("#Tennis").hide();
        $("#Volleyball").hide();
        $("#Boxing").hide();
        $("#MMA").hide();
        $("#Wrestling").hide();
        $("#Karate").toggle();
        $("#Kickboxing").hide();
        $("#MusicTheory").hide();
        $("#Dance").hide();
        $("#SoundDesign").hide();
        $("#Painting").hide();
        $("#Sculpture").hide();
        $("#Photography").hide();
        $("#DigitalArt").hide();
        $("#DrawingDance").hide();
        $("#Illustration").hide();
        $("#Gymnastics").hide();
        $("#Fencing").hide();
        $("#SkiJumping").hide();
    })
 })

 $(document).ready(function() {
    $("#n").click(function(q){
        q.preventDefault();
        $("#Swimming").hide();
        $("#Diving").hide();
        $("#Soccer").hide();
        $("#Basketball").hide();
        $("#Cricket").hide();
        $("#Rugby").hide();
        $("#Hockey").hide();
        $("#Tennis").hide();
        $("#Volleyball").hide();
        $("#Boxing").hide();
        $("#MMA").hide();
        $("#Wrestling").hide();
        $("#Karate").hide();
        $("#Kickboxing").toggle();
        $("#MusicTheory").hide();
        $("#Dance").hide();
        $("#SoundDesign").hide();
        $("#Painting").hide();
        $("#Sculpture").hide();
        $("#Photography").hide();
        $("#DigitalArt").hide();
        $("#DrawingDance").hide();
        $("#Illustration").hide();
        $("#Gymnastics").hide();
        $("#Fencing").hide();
        $("#SkiJumping").hide();
    })
 })

 $(document).ready(function() {
    $("#o").click(function(q){
        q.preventDefault();
        $("#Swimming").hide();
        $("#Diving").hide();
        $("#Soccer").hide();
        $("#Basketball").hide();
        $("#Cricket").hide();
        $("#Rugby").hide();
        $("#Hockey").hide();
        $("#Tennis").hide();
        $("#Volleyball").hide();
        $("#Boxing").hide();
        $("#MMA").hide();
        $("#Wrestling").hide();
        $("#Karate").hide();
        $("#Kickboxing").hide();
        $("#MusicTheory").toggle();
        $("#Dance").hide();
        $("#SoundDesign").hide();
        $("#Painting").hide();
        $("#Sculpture").hide();
        $("#Photography").hide();
        $("#DigitalArt").hide();
        $("#DrawingDance").hide();
        $("#Illustration").hide();
        $("#Gymnastics").hide();
        $("#Fencing").hide();
        $("#SkiJumping").hide();
    })
 })

 $(document).ready(function() {
    $("#p").click(function(q){
        q.preventDefault();
        $("#Swimming").hide();
        $("#Diving").hide();
        $("#Soccer").hide();
        $("#Basketball").hide();
        $("#Cricket").hide();
        $("#Rugby").hide();
        $("#Hockey").hide();
        $("#Tennis").hide();
        $("#Volleyball").hide();
        $("#Boxing").hide();
        $("#MMA").hide();
        $("#Wrestling").hide();
        $("#Karate").hide();
        $("#Kickboxing").hide();
        $("#MusicTheory").hide();
        $("#Dance").toggle();
        $("#SoundDesign").hide();
        $("#Painting").hide();
        $("#Sculpture").hide();
        $("#Photography").hide();
        $("#DigitalArt").hide();
        $("#DrawingDance").hide();
        $("#Illustration").hide();
        $("#Gymnastics").hide();
        $("#Fencing").hide();
        $("#SkiJumping").hide();
    })
 })

 $(document).ready(function() {
    $("#q").click(function(q){
        q.preventDefault();
        $("#Swimming").hide();
        $("#Diving").hide();
        $("#Soccer").hide();
        $("#Basketball").hide();
        $("#Cricket").hide();
        $("#Rugby").hide();
        $("#Hockey").hide();
        $("#Tennis").hide();
        $("#Volleyball").hide();
        $("#Boxing").hide();
        $("#MMA").hide();
        $("#Wrestling").hide();
        $("#Karate").hide();
        $("#Kickboxing").hide();
        $("#MusicTheory").hide();
        $("#Dance").hide();
        $("#SoundDesign").toggle();
        $("#Painting").hide();
        $("#Sculpture").hide();
        $("#Photography").hide();
        $("#DigitalArt").hide();
        $("#DrawingDance").hide();
        $("#Illustration").hide();
        $("#Gymnastics").hide();
        $("#Fencing").hide();
        $("#SkiJumping").hide();
    })
 })

 $(document).ready(function() {
    $("#r").click(function(q){
        q.preventDefault();
        $("#Swimming").hide();
        $("#Diving").hide();
        $("#Soccer").hide();
        $("#Basketball").hide();
        $("#Cricket").hide();
        $("#Rugby").hide();
        $("#Hockey").hide();
        $("#Tennis").hide();
        $("#Volleyball").hide();
        $("#Boxing").hide();
        $("#MMA").hide();
        $("#Wrestling").hide();
        $("#Karate").hide();
        $("#Kickboxing").hide();
        $("#MusicTheory").hide();
        $("#Dance").hide();
        $("#SoundDesign").hide();
        $("#Painting").toggle();
        $("#Sculpture").hide();
        $("#Photography").hide();
        $("#DigitalArt").hide();
        $("#DrawingDance").hide();
        $("#Illustration").hide();
        $("#Gymnastics").hide();
        $("#Fencing").hide();
        $("#SkiJumping").hide();
    })
 })

 $(document).ready(function() {
    $("#s").click(function(q){
        q.preventDefault();
        $("#Swimming").hide();
        $("#Diving").hide();
        $("#Soccer").hide();
        $("#Basketball").hide();
        $("#Cricket").hide();
        $("#Rugby").hide();
        $("#Hockey").hide();
        $("#Tennis").hide();
        $("#Volleyball").hide();
        $("#Boxing").hide();
        $("#MMA").hide();
        $("#Wrestling").hide();
        $("#Karate").hide();
        $("#Kickboxing").hide();
        $("#MusicTheory").hide();
        $("#Dance").hide();
        $("#SoundDesign").hide();
        $("#Painting").hide();
        $("#Sculpture").toggle();
        $("#Photography").hide();
        $("#DigitalArt").hide();
        $("#DrawingDance").hide();
        $("#Illustration").hide();
        $("#Gymnastics").hide();
        $("#Fencing").hide();
        $("#SkiJumping").hide();
    })
 })

 $(document).ready(function() {
    $("#t").click(function(q){
        q.preventDefault();
        $("#Swimming").hide();
        $("#Diving").hide();
        $("#Soccer").hide();
        $("#Basketball").hide();
        $("#Cricket").hide();
        $("#Rugby").hide();
        $("#Hockey").hide();
        $("#Tennis").hide();
        $("#Volleyball").hide();
        $("#Boxing").hide();
        $("#MMA").hide();
        $("#Wrestling").hide();
        $("#Karate").hide();
        $("#Kickboxing").hide();
        $("#MusicTheory").hide();
        $("#Dance").hide();
        $("#SoundDesign").hide();
        $("#Painting").hide();
        $("#Sculpture").hide();
        $("#Photography").toggle();
        $("#DigitalArt").hide();
        $("#DrawingDance").hide();
        $("#Illustration").hide();
        $("#Gymnastics").hide();
        $("#Fencing").hide();
        $("#SkiJumping").hide();
    })
 })

 $(document).ready(function() {
    $("#u").click(function(q){
        q.preventDefault();
        $("#Swimming").hide();
        $("#Diving").hide();
        $("#Soccer").hide();
        $("#Basketball").hide();
        $("#Cricket").hide();
        $("#Rugby").hide();
        $("#Hockey").hide();
        $("#Tennis").hide();
        $("#Volleyball").hide();
        $("#Boxing").hide();
        $("#MMA").hide();
        $("#Wrestling").hide();
        $("#Karate").hide();
        $("#Kickboxing").hide();
        $("#MusicTheory").hide();
        $("#Dance").hide();
        $("#SoundDesign").hide();
        $("#Painting").hide();
        $("#Sculpture").hide();
        $("#Photography").hide();
        $("#DigitalArt").toggle();
        $("#DrawingDance").hide();
        $("#Illustration").hide();
        $("#Gymnastics").hide();
        $("#Fencing").hide();
        $("#SkiJumping").hide();
    })
 })

 $(document).ready(function() {
    $("#v").click(function(q){
        q.preventDefault();
        $("#Swimming").hide();
        $("#Diving").hide();
        $("#Soccer").hide();
        $("#Basketball").hide();
        $("#Cricket").hide();
        $("#Rugby").hide();
        $("#Hockey").hide();
        $("#Tennis").hide();
        $("#Volleyball").hide();
        $("#Boxing").hide();
        $("#MMA").hide();
        $("#Wrestling").hide();
        $("#Karate").hide();
        $("#Kickboxing").hide();
        $("#MusicTheory").hide();
        $("#Dance").hide();
        $("#SoundDesign").hide();
        $("#Painting").hide();
        $("#Sculpture").hide();
        $("#Photography").hide();
        $("#DigitalArt").hide();
        $("#DrawingDance").toggle();
        $("#Illustration").hide();
        $("#Gymnastics").hide();
        $("#Fencing").hide();
        $("#SkiJumping").hide();
    })
 })

 $(document).ready(function() {
    $("#w").click(function(q){
        q.preventDefault();
        $("#Swimming").hide();
        $("#Diving").hide();
        $("#Soccer").hide();
        $("#Basketball").hide();
        $("#Cricket").hide();
        $("#Rugby").hide();
        $("#Hockey").hide();
        $("#Tennis").hide();
        $("#Volleyball").hide();
        $("#Boxing").hide();
        $("#MMA").hide();
        $("#Wrestling").hide();
        $("#Karate").hide();
        $("#Kickboxing").hide();
        $("#MusicTheory").hide();
        $("#Dance").hide();
        $("#SoundDesign").hide();
        $("#Painting").hide();
        $("#Sculpture").hide();
        $("#Photography").hide();
        $("#DigitalArt").hide();
        $("#DrawingDance").hide();
        $("#Illustration").toggle();
        $("#Gymnastics").hide();
        $("#Fencing").hide();
        $("#SkiJumping").hide();
    })
 })

 $(document).ready(function() {
    $("#x").click(function(q){
        q.preventDefault();
        $("#Swimming").hide();
        $("#Diving").hide();
        $("#Soccer").hide();
        $("#Basketball").hide();
        $("#Cricket").hide();
        $("#Rugby").hide();
        $("#Hockey").hide();
        $("#Tennis").hide();
        $("#Volleyball").hide();
        $("#Boxing").hide();
        $("#MMA").hide();
        $("#Wrestling").hide();
        $("#Karate").hide();
        $("#Kickboxing").hide();
        $("#MusicTheory").hide();
        $("#Dance").hide();
        $("#SoundDesign").hide();
        $("#Painting").hide();
        $("#Sculpture").hide();
        $("#Photography").hide();
        $("#DigitalArt").hide();
        $("#DrawingDance").hide();
        $("#Illustration").hide();
        $("#Gymnastics").toggle();
        $("#Fencing").hide();
        $("#SkiJumping").hide();
    })
 })

 $(document).ready(function() {
    $("#y").click(function(q){
        q.preventDefault();
        $("#Swimming").hide();
        $("#Diving").hide();
        $("#Soccer").hide();
        $("#Basketball").hide();
        $("#Cricket").hide();
        $("#Rugby").hide();
        $("#Hockey").hide();
        $("#Tennis").hide();
        $("#Volleyball").hide();
        $("#Boxing").hide();
        $("#MMA").hide();
        $("#Wrestling").hide();
        $("#Karate").hide();
        $("#Kickboxing").hide();
        $("#MusicTheory").hide();
        $("#Dance").hide();
        $("#SoundDesign").hide();
        $("#Painting").hide();
        $("#Sculpture").hide();
        $("#Photography").hide();
        $("#DigitalArt").hide();
        $("#DrawingDance").hide();
        $("#Illustration").hide();
        $("#Gymnastics").hide();
        $("#Fencing").toggle();
        $("#SkiJumping").hide();
    })
 })

 $(document).ready(function() {
    $("#z").click(function(q){
        q.preventDefault();
        $("#Swimming").hide();
        $("#Diving").hide();
        $("#Soccer").hide();
        $("#Basketball").hide();
        $("#Cricket").hide();
        $("#Rugby").hide();
        $("#Hockey").hide();
        $("#Tennis").hide();
        $("#Volleyball").hide();
        $("#Boxing").hide();
        $("#MMA").hide();
        $("#Wrestling").hide();
        $("#Karate").hide();
        $("#Kickboxing").hide();
        $("#MusicTheory").hide();
        $("#Dance").hide();
        $("#SoundDesign").hide();
        $("#Painting").hide();
        $("#Sculpture").hide();
        $("#Photography").hide();
        $("#DigitalArt").hide();
        $("#DrawingDance").hide();
        $("#Illustration").hide();
        $("#Gymnastics").hide();
        $("#Fencing").hide();
        $("#SkiJumping").toggle();
    })
 })

 

$(document).ready(function() {
   $("#btn6").click(function(){
      alert("ThankYou for your interest, we'll get back at you shortly");
      window.location.href="../index.html";
   })
})